- components/schemas/ErrorCode.yaml
- patient-information-api.yaml
* If I trigger an error condition on the PDS API sandbox, the error response includes a field "coding system" and the URL mentioned is a dummy URL.
> APM-215: Change error urls

- patient-information-api.yaml
* The URLs should link to the existing live ODS service (Already Completed)
* The PDS API spec should also refer out to the ODS API spec as a dependency - maybe in the intro - "related APIs" and also in the relevant field descriptions
> APM-198: Refer out ODS API Spec in intro

- sandbox/app.js
- specification/patient-demographics-service-api.yaml
* If I trigger an error condition on the PD API sandbox, the error response includes a field "coding system" and the URL mentioned is a dummy URL. Fix it!
> APM-215 Add error urls to error responses

- CHANGELOG.md
- README.md
* Fix references to non-existent publish/ folder (to dist/)
> APM-124 Fix references to dist/ in README

- CHANGELOG.md
- specification/components/schemas/extensions/NominatedPharmacy.yaml
* Removes ods-site-code from NominatedPharmacy org type.
> APM-198 Remove ods-site-code enum value as it will never be used

- .github/workflows/continous-integration-workflow.yaml
* :robot: Disable FHIR validation due to strange bug (Captured in ticket APM-)
> APM-247 Temporarily disable FHIR validation in CI

- .github/workflows/continous-integration-workflow.yaml
* :robot: Release creation steps may fail when workflow has been run previously - allowing these steps to skip
> APM 330 Tagging and spec upload may fail if workflow has been run previously

- .github/workflows/continous-integration-workflow.yaml
* :robot: Disable a test step that should not have been enabled.
It seems when merging APM-295 I missed that the sandbox test step had the master condition commented out. This fixes that.
> APM-364 Fix sandbox test step that was left in accidentally

- sandbox/package-lock.json
- sandbox/package.json
- scripts/deploy_proxy.sh
* BUGFIX: Fix failing deployment
Two reasons for failure:
* `deploy_proxy.sh` script was being too explicit/brittle when preparing the `dist/apiproxy/resouces/hosted/` directory - files were being excluded following refactoring of the sandbox.
* `lodash` was not listed as a sandbox top-level dependency. This is required for the project to run as an Apigee hosted target. (Although curiously this did not affect us running is locally.)
> Apm 381 sandbox hotfix

- products/application-restricted.yml
- products/user-restricted.yml
- proxies/live/apiproxy/policies/AssignMessage.Errors.InsufficientScope.xml
- proxies/live/apiproxy/policies/OAuthV2.VerifyAccessTokenWithUserRestrictedScope.xml
- proxies/live/apiproxy/targets/ig3.xml
API Products definitions may now be placed in the ```/products``` directory as separate yaml files.
> Multiple API products per proxy

- .gitignore
- poetry.lock
- pyproject.toml
- tests/functional/features/unattended_access.feature
- tests/functional/test_unattended_access.py
This ticket contains some tests for APM-1541, but they are skipped at the module level and can be safely ignored.
To use this setup:
- Look at docs for pytest and pytest-bdd
- Feel free to use the existing tests in here as examples
- Make sure you `poetry install` before running
- To run the tests, use `poetry run pytest` in the project root
Caveats:
- Be aware that these tests are not currently run in the pipeline, if you want them to be then you will need to add it
- In pytest-bdd you need to use mutable fixtures to get around carrying context between steps (e.g. creating a fixture with a dict or list value, then adding to it)
> APM-1541 Upload skipped tests so that the same setup can be used by others

- tests/functional/test_application_restricted.py
* :robot: Disables broken test
> APMSPII-588 HOTFIX: skip breaking test

- products/application-restricted-higher-ratelimit.yml
- products/user-restricted-higher-ratelimit.yml
- proxies/live/apiproxy/policies/Quota.xml
- proxies/live/apiproxy/policies/SpikeArrest.xml
* Change spike arrest resolution to per second buckets instead of per 10 ms
* Keep quota at effective 130ps, but change to a 1 minute rolling window (7800/1mins)
* Balance message handler spike arrest so the spike arrest value is always constant despite the amount of request handlers
> APM-1162 Change rate limiting policy to be kinder to burst loads

- azure/azure-release-pipeline.yml
Sandboxes in PDS don't support status checks -- they didn't used to run, and have still not figured out the cause of the failure.
> APM-1162 Don't check status on sandboxes, they don't support it

- azure/azure-release-pipeline.yml
- specification/components/schemas/NhsNumber.yaml
- specification/personal-demographics.yaml
changed:
- access mode table
- added links to API status to the table, in place of "beta" or "live"
- changed app restr. status in roadmap section
**We should review this change for consistency with other API specs**. HL7 calls itself "stable", yet we refer to Agile GDS framework, which calls it "live".
> Docs: Putting App Restricted PDS in to general release

- manifest_template.yml
At present the Int limit is specified as 40ps which is enforced as 1 request every 25 milliseconds (1000/40)
Changing to per-minute by specifying 2400pm will be enforced as 40 requests every second (2400/60) 
See the docs for more info: https://docs.apigee.com/api-platform/develop/rate-limiting#spikearrest
> RateLimiting needs to be specified per-minute to be enforced per-second

- CHANGELOG.md
- Makefile
Updated the version of the hapifhir validator to fix build issues
:warning: After this PR the validator will not work on the development VMs
I don't think the validator actually worked on the VMs anyway, but I'm not sure why. After the PR the validator will require a version of Java newer than what is available with `sudo apt install default-jre default-jdk`
> SPINEDEM-1515 fix validator in build

- azure/templates/sandbox-tests.yml
The proxy name passed to pytest in sandbox-test.yml was not dynamic enough to be used by other pipelines. This is to correct this error and make it sufficiently dynamic that the proxy name is correctly assigned according to the env/pipeline.
> SPINEDEM-1296 Correct proxy name

- azure/azure-release-pipeline.yml
- azure/templates/sandbox-tests.yml
- tests/functional/features/application_restricted.feature
The sandbox-tests.yml file needs an Apigee App ID when run in prod, and not when not. This is to correct the initial implementation of this made in PR 901.
> SPINEDEM-1296 add prod sandbox parameter to sandbox-tests

- azure/azure-release-pipeline.yml
- azure/templates/sandbox-tests.yml
- tests/conftest.py
- tests/sandbox/test_sandbox.py
Remove fixtures previously implemented.
Given the pytest-nhsd-apim package is meant to be used for nhsd-nonprod Apigee orgs, ie all environments except int, sandbox, dev, and prod, and given that these sandbox tests are to be run against nhsd-prod sandbox, a simpler solution would be to use the already in-use `config.SANDBOX_BASE_URL` constant, which is Apigee org agnostic, instead of attempting to find the url through two different methods for the sandbox environments in nhsd-nonprod and nhsd-prod.
> Spinedem 1296 remove fixtures

- tests/functional/configuration/config.py
Assignment of an unused/unset (was removed in PR 924's pds-test-int.yml) environment variable cause INT stage of Release pipeline to fail. 
As it is not used, and is no longer set in the pipeline, this change is to remove the error-raising variable assignment.
> Remove assignment of unused env var.

- tests/functional/conftest.py
- tests/functional/test_proxy_behaviour.py
- tests/functional/test_user_restricted.py
An `autouse=True` fixture was being used in the INT environment when it should not have been. 
> Spinedem 1680 move autouse fixture

- tests/conftest.py
- tests/functional/conftest.py
- tests/functional/data/users.py
- tests/functional/features/healthcare_worker_retrieve.feature
- tests/functional/features/healthcare_worker_search.feature
- tests/functional/features/healthcare_worker_update.feature
- tests/functional/features/patient_access_retrieve.feature
- tests/functional/features/patient_access_update.feature
- tests/functional/features/related_person.feature
- tests/functional/features/status_endpoints.feature
- tests/functional/steps/given.py
- tests/functional/steps/then.py
- tests/functional/steps/when.py
- tests/functional/test_patient_access.py
- tests/functional/test_smoke_tests.py
- tests/functional/test_user_restricted.py
- tests/scripts/environment.py
Add test scenario that gets an expired access token, adds it to the auth header and have a patient attempt to retrieve their details.
As part of the work, I also split up the pytest_bdd steps in to their own files as conftest was becoming cluttered.
> SPINDEM-1819 - Add expired access token test to patient access mode

- tests/functional/features/patient_access_retrieve.feature
- tests/functional/steps/given.py
- tests/functional/test_patient_access.py
Add a test to confirm a patient can access their details when using a refreshed token.
> SPINEDEM-1820 Add test for refresh tokens using Patient Access mode

- CHANGELOG.md
- azure/azure-release-pipeline.yml
- manifest_template.yml
- tests/functional/utils/apigee_api_products.py
This PR is to fix issues with the deploy pipeline failing, from jira:
The internal-qa stage, which only runs on the deployment pipeline, uses int test data as apposed to VEIT07 which internal-dev uses. This discrepancy in which telecoms snippets each record had was the cause of the failures. Following a discussion on the [APIM-support](https://nhsdigital-platforms.slack.com/archives/C016JRWN6AY/p1703161014007089) channel and within the team the current solution is to delete the internal-qa stage as the tests that are ran there are also ran on internal-dev. This will prevent test data mismatch problems, and stop us from having to refresh the int test data whenever there issues with it. The int stage of the pipeline runs smoke tests on int and is left untouched.
:information_source: This …
> Removed internal-qa stage of deploy pipeline

- azure/azure-pr-pipeline.yml
- azure/templates/pds-tests-karate.yml
- karate-tests/README.md
- karate-tests/pom.xml
- karate-tests/src/test/java/patients/TestParallel.java
:sparkles: New Feature
* Exports the html reports for karate tests as an artifact
* And running 5 tests in parallel as standard, while we're tweaking things
In the end, we won't be using cucumber reports, since we can't publish multiple files on ADO (only a single html file, which isn't much use). Exporting the regular Karate HTML reports as an artifact is good enough.
> SPINEDEM-2584 HTML Reports for Karate Tests

- specification/personal-demographics.yaml
> SPINEDEM-3725 AC2

- karate-tests/src/test/java/patients/healthcareWorker/createPatient/postPatient.feature
- proxies/live/apiproxy/policies/SpikeArrest.PatientCreate.xml
- tests/functional/features/post_patient.feature
- tests/functional/test_patient_create.py
Non-functional testing of the new POST /Patient endpoint found that 3 TPS was the maximum throughput that should be allowed. As such, the spike arrest policy and associated tests and documentation has moved from 5 TPS to 3 TPS.
> SPINEDEM-3809 Restrict Create Patient TPS

- specification/personal-demographics.yaml
- Removed [Application-restricted RESTful API - API key authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-api-key-authentication) as it is incorrect.
- Changed 'To use this access mode, use one of the following security patterns:' to reflect that there is only one security pattern.
> Removed the incorrect line 

- karate-tests/src/test/java/auth/auth-headers.js
- karate-tests/src/test/java/auth/authentication.feature
- karate-tests/src/test/java/mocks/sandbox/post-patient.js
- karate-tests/src/test/java/mocks/sandbox/supporting-functions.js
- karate-tests/src/test/java/patients/appRestricted/authentication.feature
- karate-tests/src/test/java/patients/appRestricted/createPatientError.feature
- karate-tests/src/test/java/patients/healthcareWorker/invalidHeaders/invalidHeaders.feature
1. Added logic on karate sandbox to accept requests with or without an authorization token, but validate the format of provided tokens: If an invalid authorization token format is sent, then sandbox would return an appropriate error response
2. Removed @sandbox tag from tests that check the comparative behaviour between the difference access modes.
3. Added sandbox only test to check the Invalid authorization header behaviour
4. Added example access token to mock tests
> SPINEDEM- 4099 Remove auth header from karatesandbox

- specification/components/schemas/CoverageSearch.yaml
When returning EHIC details, PDS FHIR API will place them inside a bundle along with a Meta resource, enabling `versionId` to be communicated when reading and updating.
> Define the search set bundle in which EHIC details and meta.versionID will sit

- karate-tests/src/test/java/mocks/sandbox/get-patient-search.js
- karate-tests/src/test/java/patients/appRestricted/getPatient.feature
- karate-tests/src/test/java/patients/healthcareWorker/searchForAPatient/searchParams.feature
Sandbox accepts birthdate/death-date value with or without a `eq` prepended
> SPINEDEM-4998 Correct sandbox birthdate parameter to accept with or without eq prepended

- .github/workflows/pr-lint.yaml
- .gitignore
- README.md
- scripts/calculate_version.py
**Changes:**
- Adjusted PR lint job, which links the JIRA ticket, so just run on the PR being opened.
- Minor refactoring of the `calculate_version.py` script to be more readable (think this one just shipped with the APIM default repo).
- Added a commit that includes the flag `+clearstatus` - this will mean, as long as this commit is included when merged, then the `-beta` suffix will no longer appear in the release tag that is automatically created. This version tag also appears in the OAS schema that is accessible from the public facing PDS FHIR API page: https://digital.nhs.uk/restapi/oas/320398
**Test**
- PR Lint job seems to only print once. I tested out adding an additional commit which would previously result in a new JIRA link being added. You will see that only …
> SPINEDEM-101 Add Jira description only once and remove Beta release status
