.circleci/config.yml

This PR removes an old bitbucket upload that is no longer required.

APM-124 Configure CircleCI for new github repository

---

stubserver/app.js

* Fix exception being returned when there are empty parameters

APM-187 Exception calling GET /Patient endpoint

---

patient-information-api.yaml
stubserver/app.js

* Remove the general-practioner search parameter from the patient search request.

APM-140 Remove general-practioner param

---

components/schemas/extensions/DeathNotificationStatus.yaml

APM-129 Update DeathNotificationStatus.yaml to improve wording as per issues raised by Alex

---

sandbox/mocks/Patient.json

* Fix a symlink that was breaking deploy

APM-124 Fix symlink

---

README.md

* {Routine Change}
* :exclamation: {Breaking Change}
* :robot: {Operational Change}
* :sparkles: {New Feature}
{Any other notes go here}
* [x ] Is this PR linked to a ticket in JIRA or Github issues?
* [x ] Does the branch build in CI?
* [x ] If there are any changes to the CI process, have they been verified (with evidence)?
* [x ] If any new libraries are added, are their licenses compatible with the project license?

Apm 124 readme project description improvements

---

CHANGELOG.md
specification/components/schemas/Address.yaml

* Change address lines example to show a more fully formatted address

APM-150 Add a better address lines example to Address

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
Makefile
specification/components/examples/Patient.json
specification/components/schemas/extensions/NominatedPharmacy.yaml
specification/patient-demographics-service-api.yaml

* :sparkles: Added make command for updating examples: `make update-examples`
* :wrench: Changed API base url from `/v1` to `/personal-demographics`
* :pencil2: Documentation to remove reference to ODS site code
Requires changes to Apigee:
* :robot: Change API base URL on proxy from `/v1` to `/personal-demographics`

APM-205 & APM-198 ODS Site code description and API base URL

---

CHANGELOG.md
specification/components/schemas/GeneralPractitionerReference.yaml
specification/components/schemas/Patient.yaml
specification/components/schemas/extensions/NominatedPharmacy.yaml

* Update to OAS file to include ODS links

APM-198 - ODS code links

---

specification/patient-demographics-service-api.yaml

APM-198: Update patient-demographics-service-api.yaml

---

CHANGELOG.md
specification/patient-demographics-service-api.yaml

* Updates to documentation in OAS file

APM-202 and APM-203 - API docs - explain extensions, and other tweaks

---

CHANGELOG.md
specification/patient-demographics-service-api.yaml

There are still TODOs around given names.  Also how to refer to the fields in the text
Not happy with the description of the different types of search.   Will create another branch creating a table to show the alternate fields and the resulting searches.

added more detail in search

---

specification/patient-demographics-service-api.yaml

APM-100 rework the search description

---

.github/workflows/continous-integration-workflow.yaml

* :robot: Build all branches on push

APM-247 Build all branches on push

---

.github/workflows/continous-integration-workflow.yaml

* :robot: Temporarily add a debugger action into the build pipeline to tease out master build issues.

APM-247 Add a debugger

---

.github/workflows/continous-integration-workflow.yaml
CHANGELOG.md

* :robot: Remove debugger
* :robot: Fetch all git history on checkout

APM-247 Remove debugger and fix fetch depth on checkout

---

.github/workflows/continous-integration-workflow.yaml
CHANGELOG.md
scripts/deploy.sh

* :robot: Cache npm modules
* :robot: Cache pip modules
* :robot: Tag and release successful master builds
* :robot: Upload completed specs to releases as release assets

APM-247 Improve CD Process

---

.github/workflows/continous-integration-workflow.yaml

APM-247 asset-name -> asset_name

---

.github/pull_request_template.md
.github/workflows/continous-integration-workflow.yaml
.github/workflows/pr-lint.yaml
CHANGELOG.md

* :robot: Fix caching
* :robot: Detect branch linking and post a comment
* :robot: Validate that all branch names contain a ticket number
This could be improved with a little JIRA API magic to fetch ticket summaries and so forth, but that's something for another day.

APM-247: Misc improvements to CI processes

---

specification/patient-demographics-service-api.yaml

* All parameters put into monospaced font in text body.
* Made some of the language more active.
* Made lists consistent in use (or not) of full-stops and removed initial capitals on bullet lists.
* Made the parameter change that Gurdeep had noted in the Jira ticket.
* Have **not** reviewed the Overview section. It did not appear to be part of this ticket (though it needs doing).

APM-100 Language edit only of the endpoint text. 

---

scripts/deploy_spec.sh

* :robot: Fixes getting auth tokens in deploy

[HOTFIX] APM-348 Fix auth call

---

.github/workflows/pr-lint.yaml

* :robot: Let dependabot changes through

APM-360 Change branch name rules

---

.dependabot/config.yml
.github/workflows/pr-lint.yaml
CHANGELOG.md

* :robot: Ensure only security updates are auto-merged
* :robot: Add dependabot config.

APM-360 Add dependabot-config

---

.dependabot/config.yml

* :robot: Allow PRs for all updates, only automerge for security

APM-360 Allow PRs for all updates, only automerge for security

---

.github/workflows/continous-integration-workflow.yaml
sandbox/package-lock.json
sandbox/package.json

* :robot: Rollback and pin hapi/hapi version
Fixes an issue where apigee hosted target would not run.

APM-365 Rollback hapi version

---

specification/patient-demographics-service-api.yaml

APM-100 get patient more edits

---

sandbox/app.yaml

* :robot: Set node version in app.yaml

APM-381 Set node version in app.yaml

---

sandbox/app.yaml

* :robot: Fix node version to conform to a docker image tag https://hub.docker.com/_/node?tab=tags&page=1&name=13.1.0

HOTFIX APM-381 Remove erroneous v

---

specification/patient-demographics-service-api.yaml

Found one instance of the description in the specification at line 716. I understand that this instance will be propagated to the id GET and id PATCH instances.

APM-245 Changed one instance of description

---

scripts/deploy_proxy.sh

* Update deploy script to run deploy locally on mac and linux

APM-384 Update deploy script to run on macOS

---

apiproxy/policies/AssignMessage.AddCors.xml
apiproxy/proxies/default.xml
apiproxy/targets/sandbox.xml
specification/patient-demographics-service-api.yaml

* Add CORS and CORS Preflight responses to API Proxy - required to make *Try it now* functionality work
* Make the NHSD-Session-URID field optional in the spec. See the associated JIRA for background

Apm 254 URID header field requirement fix and API "docs fix" (CORS)

---

specification/patient-demographics-service-api.yaml

APM-71 minor TA edits to Spec lines 167-168

---

specification/components/schemas/Address.yaml
specification/components/schemas/Contact.yaml
specification/components/schemas/ContactPoint.yaml
specification/components/schemas/GeneralPractitionerReference.yaml
specification/components/schemas/HumanName.yaml
specification/components/schemas/extensions/DispensingDoctor.yaml
specification/components/schemas/extensions/MedicalApplianceSupplier.yaml
specification/components/schemas/extensions/NominatedPharmacy.yaml

* updated period field descriptions to make it clear under what circumstances they might be not present

Apm 199   start and end date descriptions

---

CHANGELOG.md
README.md
apiproxy/policies/AssignMessage.AddIssuerHeader.xml
apiproxy/policies/AssignMessage.AddUserIdHeader.xml
apiproxy/policies/AssignMessage.JWKS.xml
apiproxy/policies/DecodeJWT.FromJWTHeader.xml
apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
apiproxy/policies/KeyValueMapOperations.GetVariables.xml
apiproxy/policies/LookupCache.JWKS.xml
apiproxy/policies/PopulateCache.JWKS.xml
apiproxy/policies/ServiceCallout.GetJWKS.xml
apiproxy/policies/VerifyJWT.FromJWTHeader.xml
apiproxy/targets/ig3.xml

* Verify the signature of the incoming JWT

Apm 432 verify jwt token signature

---

CHANGELOG.md
apiproxy/targets/ig3.xml

* Additional check that required header `NHS-Session-URID` is not blank/empty when present

Apm 245 role header must not be empty

---

.gitignore
poetry.lock

* Upgrades pyyaml dependency so that dependabot can resolve it

APM-517 Update pyyaml dependency

---

specification/patient-demographics-service-api.yaml

Apm 225 change to testing section ta

---

sandbox/routes/patient/get-patient.js
sandbox/services/patient-searcher.js
specification/patient-demographics-service-api.yaml
tests/e2e/personal-demographics-service-sandbox.json

* Fixing the 'Run with Postman' button to point to the correct path.
* Making the date 'eq' prefix optional.

API-504 | Run with Postman Sandbox Fix

---

specification/patient-demographics-service-api.yaml

apm-225 tech author re-edit of the Testing section

---

specification/patient-demographics-service-api.yaml

* Routine Change - spec update only

APM-502 - add base URLs to spec

---

specification/patient-demographics-service-api.yaml

Apm 502 base url docs

---

.github/workflows/continous-integration-workflow.yaml

* :robot: Re-enables tagging so that Azure builds can be version-aware

APM-501 Re-add releases and tagging

---

specification/personal-demographics.yaml

APM-502 - environment base URLs

---

specification/personal-demographics.yaml

APM-403 - search doc updates

---

specification/personal-demographics.yaml

Apm 434 clinical safety match weight

---

proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/proxies/default.xml

* :robot: Adds template string into proxy def so it can deployed on many paths to allow namespacing

APM-501 Make proxy tempaltable to set service base path

---

terraform/main.tf

* quick fix: no API Product for Sandbox Environments

No API Product for the Sandbox

---

terraform/main.tf

fix logic error

---

CHANGELOG.md
Makefile
terraform/main.tf

* Remove TODO in personal-demographics product description

APM-795 Remove TODO description

---

tests/e2e/regression-pack.json

For the time being I have removed the Update based tests as they are intermittently failing.

APM-501 fixed failing Postman tests

---

terraform/main.tf
terraform/variables.tf

* :robot: Deploys sandboxes for PRs alongside live proxies.

APM-518 Allow forcing a sandbox deploy on a live env

---

tests/e2e/regression-pack.json
tests/e2e/test-runner.js

Removed both ASID and UUID headers from being sent in the Regression tests.

Removed both ASID and UUID headers from Regression tests

---

specification/personal-demographics.yaml

* Change some of the links on the documentation

APM-835 Update Spec Links

---

tests/e2e/test-runner.js

* :robot: Increase timeout on test runner so that it stops bombing out

APM-954 Timeout increase for test runner

---

specification/personal-demographics.yaml

* Search descriptions requested by Tone.

APM-885 | Search description changes

---

specification/personal-demographics.yaml

* Sensitive Patient description tweaks

AMP-704 | Sensitive Patient description tweaks

---

tests/e2e/regression-pack.json

In order to prevent failing pipeline builds, the failing tests have been set to be skipped. These are being fixed in isolation and will be re-introduced once fixed.

Skipping failing pipeline Smoke Tests

---

tests/e2e/e2e.json

Updated the e2e collection to match Postman master branch -- which contains the latest tests

Updated e2e pack to include latest tests from Postman

---

.github/workflows/post-pr-workflow.yml

* :robot: Tears down review sandboxes post PR

APM-1016 Tear down infra post PR

---

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml

* Adding If-match header to CORS

APM-1073 | Adding if-match header to CORS

---

.gitignore
CHANGELOG.md
proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
proxies/sandbox/apiproxy/proxies/default.xml
tests/e2e/smoke.json

Reverts NHSDigital/personal-demographics-service-api#240

AMB-67 Add _ping endpoint to the proxy. Update gitignore

---

specification/personal-demographics.yaml

ADZ-137 Update link to test data pack

---

tests/e2e/regression-pack.json

Removed failing test from pipeline for further investigation

Removed failing Postman test for further investigation

---

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/policies/FlowCallout.LogToSplunk.xml
proxies/sandbox/apiproxy/proxies/default.xml

apm-370: add splunk logging postclient flow

---

azure-pipelines.yml

remove caching

---

tests/e2e/test-runner.js

Updated the Postman tests to use the new simulated NHS ID journey

Update tests to use the new simulated NHS ID journey

---

sandbox/mocks/Minimal_Patient.json
sandbox/mocks/Minimal_PatientSearch.json
sandbox/services/patients.js
scripts/duplicate_examples.sh
scripts/format_examples.py
scripts/generate_examples.py
scripts/update_examples.sh
specification/components/examples/Minimal_Patient.json
specification/components/examples/Minimal_PatientSearch.json
specification/personal-demographics.yaml
tests/e2e/sandbox.json

* Adding a patient to the sandbox that has minimal data - so that all patch adds can be made

APM-1175 | Empty Patient

---

azure-pipelines.yml

Only deploy the sandbox in the sandbox environments.

APM-1265 Restrict environments for sandbox deployment

---

specification/personal-demographics.yaml

Spec tweaks - PDS update is in prod and legal use link

---

azure-pipelines.yml
specification/personal-demographics.yaml

* Fixes a small typo in the spec

APM-1162 Fix typo

---

specification/components/schemas/ErrorCode.yaml
specification/components/schemas/OperationOutcome.yaml
specification/personal-demographics.yaml

* Adding diagnostics to OperationOutcome

APMSPII-343 | Adding diagnostics to OperationOutcome

---

specification/personal-demographics.yaml

removed mention of consent from spec

---

tests/e2e/regression-pack.json

Updated the tests based on the changes highlighted in `APMSPII-343`

Updated tests based on changes for operation outcome response

---

specification/personal-demographics.yaml

Apmspii-141-Contact-Prefs-portal-amend

---

azure-pipelines.yml

* fix: sandbox not deploying for internal-qa-sandbox environment

fix: sandbox not deploying for internal-qa-sandbox environment

---

CHANGELOG.md
README.md
specification/components/schemas/ETag.yaml
specification/personal-demographics.yaml

* Improve Etag explaination
* Update readme with correct link
* Add changelog entry for previous commit

APMSPII-226 | Etags description, readme and changelog update

---

specification/personal-demographics.yaml

1. moved `temp` address section of spec in to the business rules as that's what it is
2. **line 1149** `text` rather than `address.text` as the spec section is address and this is more consistent with rest of spec

Apmspii 321 further spec changes

---

azure/azure-release-pipeline.yml

APM-1315 add name of repo

---

specification/personal-demographics.yaml

Changes to the network access section of the OAS spec

---

specification/personal-demographics.yaml

Update personal-demographics.yaml - INT env't tweaks

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/pds-tests.yml

Fix PDS tests invocation

---

azure/azure-pr-pipeline.yml
azure/templates/pds-tests.yml

smoke test the correct endpoint

---

azure/azure-release-pipeline.yml

Disable ref environment

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
proxies/live/apiproxy/policies/AssignMessage.Errors.MissingASID.xml
proxies/live/apiproxy/targets/ig3.xml
tests/e2e/smoke.json

* Add in some templating and config for requiring (or not requiring) an ASID

Apm 1276 asid required

---

azure/project.yml

Remove API Product description

---

proxies/live/apiproxy/policies/AssignMessage.Errors.MissingASID.xml
proxies/live/apiproxy/targets/ig3.xml

APM-1276 Correct condition

---

azure/azure-release-pipeline.yml

specify api product availability

---

azure/azure-release-pipeline.yml

Apm 1381 re add internal dev

---

proxies/live/apiproxy/targets/ig3.xml

* :robot: Fixes a bad condition in ASID inclusion
See comment [here](https://nhsd-jira.digital.nhs.uk/browse/APM-1429?focusedCommentId=679326&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-679326) for explanation

APM-1429 Explicitly require the value 'true'

---

specification/personal-demographics.yaml

Apmspii 425 correct reqid spec

---

azure/azure-pr-pipeline.yml
proxies/live/apiproxy/targets/ig3.xml

* Fixes inclusion/exclusion of the asid required policy

APM-1429 Try explicit true string

---

specification/personal-demographics.yaml

as-APMSPII-207-language-docs-changes

---

specification/personal-demographics.yaml

APMSPII-472 URID fixing broken link

---

azure/azure-build-pipeline.yml
package.json

Apm 000 sandbox test publish fix

---

specification/personal-demographics.yaml

as-apmspii-330-relatedPerson-requestID-docs-amendment

---

specification/personal-demographics.yaml

Ms apmspii 511 app restricted update

---

.github/workflows/continous-integration-workflow.yaml
.github/workflows/pr-lint.yaml

* Add env var to enable failing command

APM-000 add env to allow command

---

proxies/live/apiproxy/resources/jsc/SetStatusResponse.js

APMSPII-500 - changed variable that status response is set to

---

azure/azure-release-pipeline.yml

* Add missing keys to release pipeline

APM-1622 Add keys to release pipeline

---

azure/azure-release-pipeline.yml

APM-1162 Adding ref to list of release deployments

---

specification/personal-demographics.yaml

Update personal-demographics.yaml to better describe message ID and correlation ID

---

.gitignore
tests/functional/test_application_restricted.py

Debug internal-qa test

---

specification/personal-demographics.yaml

Update personal-demographics.yaml - changes to auth section re. RBAC

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/common/setup-newman-tests.yml
azure/templates/pds-int-tests.yml
azure/templates/pds-tests.yml

In order to fix secure file download which is broken in PDS
----

APM-1162 Remove unused environment parameter from PDS test templates

---

products/application-restricted-higher-ratelimit.yml
products/application-restricted.yml
products/user-restricted-higher-ratelimit.yml
products/user-restricted.yml

APM-1553 Increase rate limit for ref

---

specification/personal-demographics.yaml

as-apmspii-586-postman-collection-docs-amendments

---

azure/azure-release-pipeline.yml

AMB-471 - enable _status for monitoring

---

manifest.yml
specification/personal-demographics.yaml

Update personal-demographics.yaml to include info about patient geographical location

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

apm-1351: pin pds utils to v0.1.0 to protect from upstream changes

---

manifest.yml
specification/components/schemas/OperationOutcome.yaml
specification/personal-demographics.yaml

Apmspii 571   spec   rework error tables

---

specification/components/schemas/PatientSearch.yaml

Updated grammatical errors.

---

.gitignore
azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/pds-int-tests.yml
azure/templates/pds-tests.yml

Mm apm 1351 aws build agents

---

azure/azure-release-pipeline.yml

Provide client id and secret for user restricted tests

---

specification/personal-demographics.yaml

removed all the contractions from the spec apart from the Message description as it is a code change.

Remove contractions from spec

---

specification/components/schemas/Address.yaml
specification/components/schemas/BirthDate.yaml
specification/components/schemas/Contact.yaml
specification/components/schemas/ContactPoint.yaml
specification/components/schemas/DeceasedDateTime.yaml
specification/components/schemas/HumanName.yaml
specification/components/schemas/Meta.yaml
specification/components/schemas/Patient.yaml
specification/components/schemas/PatientSearch.yaml

Apmspii 646 b remove usage of future tense

---

specification/components/schemas/NhsNumber.yaml
specification/components/schemas/PatientReference.yaml

Ms adz 906 fix nhs number

---

specification/components/schemas/XCorrelationId.yaml
specification/components/schemas/XRequestID.yaml
specification/personal-demographics.yaml

Correlation And Request ID ts-APMSPII-647-DocsUpdateAddCorelation

---

manifest_template.yml

* Config change: reconfigure API Products in Ref to support a higher ratelimit for testing purposes

increase ref ratelimit to 525TPS for V&P testing purposes

---

tests/user_restricted/test_user_restricted.py
tests/user_restricted/utils/check_oauth.py
tests/user_restricted/utils/helpers.py

FixIntermittentTestFailures

---

manifest_template.yml

-------
- Add the spec_guid to the manifest template for splunk logging.
- Update api.id->api.guid, the preferred name.

APM-1572 Add spec_guid to manifest_template.yml

---

specification/personal-demographics.yaml

APMSPII-744 remove question mark from section heading

---

manifest_template.yml
tests/functional/test_application_restricted.py

* convert default ratelimit to 300pm from 5ps

APM-2017 convert default ratelimit to 300pm from 5ps

---

tests/functional/conftest.py
tests/functional/features/proxy_behaviour.feature
tests/functional/test_application_restricted.py
tests/functional/test_proxy_behaviour.py

* Fixes to new bdd tests introduced [in 565.](https://github.com/NHSDigital/personal-demographics-service-api/pull/565)

Apmspii 627 hotfix test

---

specification/components/schemas/extensions/DispensingDoctor.yaml
specification/components/schemas/extensions/MedicalApplianceSupplier.yaml
specification/components/schemas/extensions/NominatedPharmacy.yaml
specification/personal-demographics.yaml
tests/functional/test_application_restricted.py

* Minor corrections/updates to the PDS API Spec and Schemas
In fixing the failing Jenkins overnight jobs 'Compare Schema' and 'Compare Spec' some subtle issues were found. This update corrects them.

Apmspii 653 bugfix schemas

---

tests/user_restricted/test_user_restricted.py

* Hotfix for failing `test_retrieve_patient` 
* The does a soft compare for shape of response
https://nhsd-jira.digital.nhs.uk/secure/RapidBoard.jspa?rapidView=2266&projectKey=APMSPII&view=detail&selectedIssue=APMSPII-909

Apmspii 909 user restricted test failing

---

specification/components/schemas/RetryAfter.yaml
specification/personal-demographics.yaml

Include Retry-After header schema in the PATCH 503 response

---

specification/personal-demographics.yaml

Correct header name from ETag to Retry-After

---

azure/azure-release-pipeline.yml

* Adds depends on internal-dev for qa in pipeline

Sync Update release branch

---

specification/personal-demographics.yaml

Updated the links and text 
from NHS Identity or nhs-identity
To NHS Care Identity Service 2 (NHS CIS2)

apmspii-945-re-branding-nhs-identity-to-nhs-cis2

---

specification/personal-demographics.yaml

Adding NEMs events to PDS related APIs

---

specification/personal-demographics.yaml

DH APMSPII 985 - update postman collection

---

pyproject.toml
tests/functional/conftest.py

Dh apmspii 986 fix sync wrap test suite failing tests

---

specification/components/schemas/HumanName.yaml

Update spec with spaces in names

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/pds-tests.yml
pyproject.toml
tests/user_restricted/test_user_restricted.py
tests/user_restricted/utils/helpers.py

* Remove postman tests from pipeline

Apmspii 1019 smoke tests to python

---

specification/personal-demographics.yaml

* Move verify nhs number into API CAN functionality

APMSPII-915 Update API functionality list

---

specification/personal-demographics.yaml

dh-APMSPII-872-docs content location header

---

proxies/sandbox/apiproxy/policies/AssignMessage.AddAccessContolExposeHeader.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/proxies/default.xml
specification/personal-demographics.yaml

DH APMSPII-1012 expose headers try this api

---

specification/personal-demographics.yaml

APMSPII-1090 Docs change update with valid URID

---

specification/personal-demographics.yaml

fixed link to NHS no in data dictionary

---

specification/components/schemas/NhsNumber.yaml

NhsNumber schema link changed

---

azure/azure-release-pipeline.yml

Reinstate the pipelne test stages

---

specification/personal-demographics.yaml

remove passive language on PDS FHIR being primary choice

---

azure/azure-release-pipeline.yml

APMSPII-575 Use INT Client ID

---

azure/azure-release-pipeline.yml
azure/templates/pds-tests-int.yml

APMSPII-575 Point internal-dev client id to right params

---

azure/azure-release-pipeline.yml

APMSPII-575 Per environment config

---

tests/user_restricted/configuration/config.py

point to correct identity service when using int environment

---

azure/templates/pds-tests-int.yml

fix publish test report step

---

tests/user_restricted/configuration/config.py

Updated test config logic to take into account internal-qa environment

---

tests/user_restricted/configuration/config.py

Amended logic to determine spine_hostname value

Amended logic to determine spine_hostname value

---

azure/azure-release-pipeline.yml

Disable test execution against internal-qa

---

specification/personal-demographics.yaml

Adding the term sensitive patient to the PDS spec

---

manifest_template.yml

reduce ref ratelimit for testing purposes

---

specification/components/schemas/Address.yaml
specification/components/schemas/ContactPoint.yaml
specification/components/schemas/ErrorCode.yaml
specification/components/schemas/GeneralPractitionerReference.yaml
specification/components/schemas/HumanName.yaml
specification/components/schemas/Identifier.yaml
specification/components/schemas/Meta.yaml
specification/components/schemas/OperationOutcome.yaml
specification/components/schemas/Patient.yaml
specification/components/schemas/PatientReference.yaml
specification/components/schemas/PatientSearch.yaml
specification/components/schemas/RelatedPerson.yaml
specification/components/schemas/codeable/ContactRelationship.yaml
specification/components/schemas/codeable/Language.yaml
specification/components/schemas/codeable/NHSNumberVerificationStatus.yaml
specification/components/schemas/codeable/Relationship.yaml
specification/components/schemas/extensions/AddressKey.yaml
specification/components/schemas/extensions/BirthPlace.yaml
specification/components/schemas/extensions/Communication.yaml
specification/components/schemas/extensions/ContactPreference.yaml
specification/components/schemas/extensions/ContactRank.yaml
specification/components/schemas/extensions/CopyCorrespondence.yaml
specification/components/schemas/extensions/DeathNotificationStatus.yaml
specification/components/schemas/extensions/DispensingDoctor.yaml
specification/components/schemas/extensions/MedicalApplianceSupplier.yaml
specification/components/schemas/extensions/NHSNumberVerificationStatus.yaml
specification/components/schemas/extensions/NominatedPharmacy.yaml
specification/components/schemas/extensions/OtherContactSystem.yaml

**Descriptiom**
Remove readOnly label from response schemas.
More detail in: [ADZ-894](https://nhsd-jira.digital.nhs.uk/browse/ADZ-894)

ADZ-894 Remove readOnly label from schemas

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/pds-tests-int.yml
azure/templates/pds-tests.yml

Refactor the reading of pipeline env variables

---

azure/azure-release-pipeline.yml

Format pipeline script

---

azure/azure-release-pipeline.yml
azure/templates/pds-tests-internal-qa.yml

AMB-747 create new test template for internal-qa

---

.gitignore
proxies/live/apiproxy/policies/RaiseFault.500UnknownError.xml
proxies/live/apiproxy/targets/sync-wrap.xml
proxies/sandbox/apiproxy/policies/AssignMessage.Errors.Default.xml
proxies/sandbox/apiproxy/policies/AssignMessage.Set500UnknownErrorStatusResponse.xml
proxies/sandbox/apiproxy/policies/RaiseFault.500UnknownError.xml
proxies/sandbox/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/targets/sync-wrap.xml
sandbox/.eslintrc.js
sandbox/src/helpers/simulate-spine-errors-helper.js
sandbox/src/routes/patient/polling.js
specification/personal-demographics.yaml

apmspii 1135 change polling 422 error

---

sandbox/.eslintrc.js
sandbox/src/helpers/simulate-spine-errors-helper.js

apmspii 1135 fix optional chaining not supported in sandbox

---

manifest_template.yml

* Increase production rate limit from 240 TPS to 270 TPS

APMSPII-1127 Increase Production Rate Limit to 270 TPS

---

manifest_template.yml

Revert changes to ref rate limit to its original values

APMSPII-1125 revert changes to decreasing ref rate limit

---

azure/azure-release-pipeline.yml

Disable /_status monitoring for ref

---

azure/templates/pds-tests.yml
tests/functional/config_files/config.py
tests/functional/config_files/environment.py
tests/functional/conftest.py

AMB-803 use internal-testing app for patient access test

---

manifest_template.yml

APMSPII-1164 Change rate limit in ref to 15 TPS

---

azure/templates/pds-tests.yml

APMSPII-1133 Fix for env vars

---

manifest_template.yml

APMSPII-1169 Revert ref rate limit

---

specification/personal-demographics.yaml

updated spec to clarify alpha and beta modes for patient and healthcare worker access modes

amb 832 alpha & beta clarity

---

specification/personal-demographics.yaml

remove additional )

---

specification/components/schemas/OperationOutcome.yaml
specification/personal-demographics.yaml

Updated one of the error examples displayed in the Specification to include the 'diagnostics' field which is returned in some circumstances. 

Updated example error in spec to include diagnostics field

---

specification/personal-demographics.yaml

Ts apmspii 1175 unknown address in retrieval

---

manifest_template.yml

* :robot: Int environment rate limit increase from 5TPS to 20TPS

APMSPII-1196: Increase Int rate limit to 20TPS

---

specification/personal-demographics.yaml

NHS UK wording via Steven Koch

---

tests/functional/features/application_restricted.feature
tests/functional/test_application_restricted.py

Allow some time for API Product change to take effect

---

specification/personal-demographics.yaml

PDS spec file has definitions that are defined 'inline'. These definitions should be defined under #/components/... instead. This will make the spec easier to read but most importantly will create a spec that we can feed into the code-gen module.

AMB-918 - update spec with internal references

---

proxies/live/apiproxy/policies/RaiseFault.PatchMethodNotAllowedAppRestricted.xml
tests/functional/features/application_restricted.feature
tests/functional/test_application_restricted.py

Updated the error message code which is thrown when an application restricted app attempts a PATCH request.

Changed issue.code value for AppRestricted error message

---

proxies/live/apiproxy/policies/RaiseFault.PatchMethodNotAllowedAppRestricted.xml
tests/functional/features/application_restricted.feature

Reverted change to issue.details.coding.code

---

specification/components/schemas/ManagingOrganization.yaml

APMSPII-1180 Orphan Docs - fix typo

---

specification/personal-demographics.yaml

Fix typo in Spec

---

specification/personal-demographics.yaml

Added service level section as part of ADZ-1612

---

specification/personal-demographics.yaml

Reword the description for the Retry-After header

---

specification/personal-demographics.yaml

Doc update

---

manifest_template.yml

https://nhsd-jira.digital.nhs.uk/browse/APM-2863

APM-2863 Add mock identity service proxy to products

---

proxies/live/apiproxy/policies/AssignMessage.AddPatientAccessHeader.xml
tests/functional/test_patient_access.py

APMSPII-1269: Rename `NHSD-Patient` header to `NHSD-NHSLogin-User`

---

azure/templates/pds-tests-int.yml

Updated the oauth endpoint for the INT tests to point to the mock endpoint

Updated the oauth endpoint for the INT tests

---

specification/personal-demographics.yaml

Added tag to fix broken page link

---

specification/personal-demographics.yaml

PDS spec now explains that there is such a thing as technical conformance, rather than leaving it until you are onboarding. See slack: https://nhsdigital-platforms.slack.com/archives/G01QWFU5FN2/p1648044866766809?thread_ts=1648042979.393189&cid=G01QWFU5FN2

added agreed paragraph and hyperlink

---

specification/personal-demographics.yaml

Now that DOS takes care of it all, there is no need for step specific instructions.

removed non-digital instructions

---

specification/personal-demographics.yaml

Changes as part of ADZ-1875

---

specification/personal-demographics.yaml

Reverts NHSDigital/personal-demographics-service-api#809

Revert "Changes as part of ADZ-1875"

---

.gitignore
manifest_template.yml
specification/personal-demographics.yaml
tests/functional/conftest.py
tests/functional/test_patient_access.py

Apm 1297 patient access scope case sensitivity

---

specification/personal-demographics.yaml

FHIR Conformance statement change

---

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml

Updated CORS policies to allow nhsd-end-user-organisation-ods

---

manifest_template.yml
specification/personal-demographics.yaml

* Updated documentation and manifest for patient-access mode move to beta

SPINEDEM-651 Updated documentation and manifest 

---

CHANGELOG.md
README.md

Updated setup instructions in readme, backfilled changelog

---

CHANGELOG.md
specification/personal-demographics.yaml

Update personal-demographics.yaml - added open source section

---

tests/conftest.py
tests/sandbox/conftest.py

The pytest plugin must be declared in the top-level conftest.

SPINEDEM-1296-move-pytest-plugin

---

azure/templates/sandbox-tests.yml

Remove `displayName` from sandbox-test.yml.

SPINEDEM-1296 Remove displayName

---

azure/templates/sandbox-tests.yml

Removed displayName for call to template so yaml files are valid.

Removed displayName for call to template.

---

azure/templates/sandbox-tests.yml

When grabbing secrets from AWS Secrets Manager, the config has to be set. This PR is to add a step that sets the config, to grab the secret, `APIGEE_APP_ID`.

SPINEDEM-1296 Assume AWS role

---

azure/templates/pds-tests-int.yml

Added APIGEE_ACCESS_TOKEN for int

SPINEDEM-1289 Added APIGEE_ACCESS_TOKEN for int

---

azure/templates/pds-tests-int.yml

SPINEDEM-1289 Added apigee-app-id

---

tests/user_restricted/test_user_restricted.py

SPINEDEM-1289 Drafting out smoke tests

---

.flake8
azure/templates/pds-tests-int.yml
tests/user_restricted/test_user_restricted.py
tests/user_restricted/utils/helpers.py

SPINEDEM-1680 Undraft smoke tests

---

azure/templates/pds-tests-int.yml

APIGEE_ORGANIZATION needs to be passed to pytest when running tests in smoke tests for INT.

SPINEDEM-1680 - Add apigee org to cli args in INT tests.

---

specification/personal-demographics.yaml

Add table of ranges of acceptable characters for name data in place of 'utf-8 encodable'.

Add table of acceptable character ranges.

---

specification/personal-demographics.yaml

Amend the description of how searching on given name works.

Amend description of given name searching behaviour.

---

specification/components/schemas/extensions/Communication.yaml

Amend communication extension definition to reflect more accurately the expected format.

SPINEDEM-1452 Amend communication extension description

---

specification/personal-demographics.yaml

SPINEDEM-1762: Documentation update

---

specification/components/schemas/BirthDate.yaml
specification/components/schemas/DeceasedDateTime.yaml
specification/components/schemas/Meta.yaml
specification/components/schemas/Patient.yaml
specification/components/schemas/PatientSearch.yaml
specification/personal-demographics.yaml

Spinedem 1570 documentation update

---

tests/functional/data/patients.py
tests/functional/data/updates.py
tests/functional/features/patient_access_update.feature
tests/functional/steps/given.py
tests/functional/steps/then.py
tests/functional/steps/when.py
tests/functional/test_patient_access.py
tests/functional/test_user_restricted.py

Add happy path test for patient access update

SPINEDEM-1821 SPINEDEM-1822 Add happy path test for patient access update

---

tests/functional/features/patient_access_retrieve.feature
tests/functional/test_patient_access.py

Ensure that a patient cannot search for another patient.

SPINEDEM-1822 Ensure patient access mode has a test for searching for a patient

---

tests/functional/test_smoke_tests.py

removes status check from smoke tests

---

karate-tests/src/test/java/patients/healthcareWorker/createPatient/postPatient.feature

SPINEDEM-2333: Updated familyName

---

specification/components/schemas/Gender.yaml
specification/personal-demographics.yaml

SPINEDEM-2339

---

manifest_template.yml

SPINEDEM-3315 Increased prod rate limit to 1500tps

---

karate-tests/src/test/java/patients/TestMockParallel.java
karate-tests/src/test/java/patients/TestParallel.java
karate-tests/src/test/java/patients/TestSchemaParallel.java
karate-tests/src/test/java/patients/TestSmoke.java
karate-tests/src/test/java/patients/appRestricted/getPatient.feature
karate-tests/src/test/java/patients/healthcareWorker/getPatientDetails/getPatientRelatedPerson.feature
karate-tests/src/test/java/patients/healthcareWorker/searchForAPatient/searchParams.feature
package-lock.json
package.json

This branch fixes the failing smoke tests, which only run in the deploy pipeline and against the int environment.
The test that was failing was an application restricted access mode test, which wasn't previously ran in pytest. It may be worth covering this at some point, but I don't think it's necessary to get the pipeline in a passing state.
There were some other cases for other endpoints for healthcare access mode that were previous covered by pytest, this branch covers them in karate.

SPINEDEM-3315 Fixed smoke tests

---

specification/personal-demographics.yaml

SPINEDEM-3485: provisional docs update

---

azure/azure-release-pipeline.yml

SPINEDEM-3315 Set prod producer approval to true

---

specification/personal-demographics.yaml

Spinedem 3378

---

karate-tests/src/test/java/patients/patientAccess/updatePatient.feature

Updated the test data for "Patient can replace their mobile number scenario"

SPINEDEM-3684 fix patient contact details test

---

karate-tests/src/test/java/patients/patientAccess/getPatient.feature
karate-tests/src/test/java/patients/patientAccess/getPatientRelatedPerson.feature
karate-tests/src/test/java/patients/patientAccess/updatePatient.feature
proxies/live/apiproxy/resources/jsc/RestrictRequest.js

* Adds patient access mode security related tests

SPINEDEM-3794 -Improve Patient Access Mode Security

---

karate-tests/src/test/java/mocks/sandbox/get-patient-search.js
karate-tests/src/test/java/mocks/stubs/searchResponses/countrycode_mobile_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/cuff_superseded_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/dateOfDeath_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/fuzzy_multimatch_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/fuzzy_single_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/general_practitioner_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/historic_email_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/multimatch_phoneAndEmail_searchset.json
karate-tests/src/test/java/mocks/stubs/searchResponses/other_givenName.json
karate-tests/src/test/java/mocks/stubs/searchResponses/postalcode_wildcard_searchset.json
karate-tests/src/test/java/patients/healthcareWorker/searchForAPatient/searchParams.feature
karate-tests/src/test/java/patients/patientAccess/updatePatient.feature

* Adds additional search for a patient regression scenarios

SPINEDEM-3894- search for a patient regression scenarios

---

azure/overnight-test-against-internal-dev-pipeline.yml
karate-tests/src/test/java/patients/healthcareWorker/searchForAPatient/searchParams.feature

SPINEDEM_ 3624 fix overnight pipeline config issues

---

karate-tests/src/test/java/mocks/sandbox/patch-patient.js
karate-tests/src/test/java/mocks/sandbox/post-patient.js
karate-tests/src/test/java/mocks/sandbox/stubs.js
karate-tests/src/test/java/mocks/stubs/patientResponses/patient_9733162051.json
karate-tests/src/test/java/patients/healthcareWorker/updatePatientDetails/addAndRemove.feature

Removed stateful behaviour of Karate sandbox and updated addAndRemove.feature related tests.

SPINEDEM-3403 - Removed stateful behaviour of Karate sandbox

---

karate-tests/karate-config.js
karate-tests/src/test/java/mocks/sandbox/get-patient-search.js
karate-tests/src/test/java/mocks/sandbox/operations.js
karate-tests/src/test/java/mocks/sandbox/patch-patient.js
karate-tests/src/test/java/patients/TestParallel.java
specification/components/examples/requests/PatientPatch/add-name.json
specification/personal-demographics.yaml

- Added OAS example scenarios in the karate sandbox
- Corrected default value on the OAS file
- Corrected example patch request on the OAS file

SPINEDEM-3405 - OAS examples are covered by the karate sandbox

---

karate-tests/src/test/java/helpers/utils.feature
specification/components/schemas/EndlessPeriod.yaml

This is used for the create patient schema in spine. Adding as part as this PR as it is outside the create/schemas directory and causing problems for the schema compare job.

SPINEDEM-3163 Added endless period

---

karate-tests/src/test/java/helpers/utils.feature
karate-tests/src/test/java/mocks/sandbox/post-patient.js
karate-tests/src/test/java/mocks/stubs/errorResponses/TOO_MANY_VALUES_SUBMITTED.json
karate-tests/src/test/java/patients/healthcareWorker/createPatient/postPatient.feature

* Added additional scenarios for NHS number allocation

SPINEDEM- 3896 Additional scenarios for NHS number allocation

---

karate-tests/src/test/java/helpers/utils.feature
karate-tests/src/test/java/patients/patientAccess/updatePatient.feature
karate-tests/src/test/java/patients/requestDetails/add/nominatedPharmacy.json

* Added below patient access scenarios
1. Patient can add temporary address and remove it
2. Patient can add and remove nominated pharmacy

SPINEDEM-3897 - Add additional patient access related tests

---

karate-tests/src/test/java/patients/appRestricted/getPatient.feature
karate-tests/src/test/java/patients/appRestricted/getPatientsRelatedPerson.feature
karate-tests/src/test/java/patients/appRestricted/updatePatientError.feature

* Added below app restricted access related regression scenarios
- search for a patient and get a single match result returned
- Too many matches message when search result return more than one match
- get a patient's details
- get a patient's related people
- negative test to prove app restricted can't update

SPINEDEM-3898 - Added additional regression scenarios for app restricted

---

azure/overnight-test-against-internal-dev-pipeline.yml

* Adds python version while installing poetry

SPINEDEM-4422 Add python version on overnight pipeline job

---

karate-tests/src/test/java/mocks/sandbox/get-coverage-retrieve.js
karate-tests/src/test/java/patients/patientAccess/getCoverageDetailsErrors.feature
postman/patient-demographics-sandbox.postman_collection.json

Additional EHIC sandbox scenarios

SPINEDEM-4503 Additional EHIC sandbox scenarios

---

.github/workflows/continuous-integration-workflow.yaml
karate-tests/src/test/java/patients/appRestricted/getCoverage.feature
karate-tests/src/test/java/patients/appRestricted/updateCoverage.feature
karate-tests/src/test/java/patients/healthcareWorker/getCoverage.feature
karate-tests/src/test/java/patients/healthcareWorker/updateCoverage.feature
karate-tests/src/test/java/patients/patientAccess/getCoverageDetails.feature
karate-tests/src/test/java/patients/patientAccess/getCoverageDetailsErrors.feature
karate-tests/src/test/java/patients/patientAccess/updateCoverageDetails.feature
karate-tests/src/test/java/patients/patientAccess/updateCoverageDetailsErrors.feature
specification/components/paths/coverage-get.yaml
specification/components/paths/coverage-post.yaml
specification/components/paths/patient-search.yaml

SPINEDEM-4461 removed no-oas annotation

---

karate-tests/src/test/java/mocks/sandbox/get-patient-search.js
karate-tests/src/test/java/mocks/stubs/errorResponses/NOT_SUPPORTED_SEARCH.json
karate-tests/src/test/java/patients/healthcareWorker/searchForAPatient/oasExamples.feature
postman/patient-demographics-sandbox.postman_collection.json

sandbox environment warns user when there is no default search responses

SPINEDEM-4564_sandbox environment warns user when there is no default search responses

---

azure/templates/sandbox-tests.yml
specification/components/schemas/CountryCode.yaml
specification/components/schemas/Coverage.yaml

These are the same changes as stated under #1110. That PR seems to have lost its checks.

Spinedem 4659 update ehic field names in schema daha

---

specification/components/schemas/CountryCode.yaml
specification/components/schemas/Coverage.yaml

Added new EHIC descriptions x5. Moved the country code description from identifier field up a level to the assigner field. Made country code description more succinct following product review.

Spinedem 4659 update ehic field names in schema

---

karate-tests/src/test/java/mocks/sandbox/post-coverage.js
karate-tests/src/test/java/patients/patientAccess/updateCoverageRequests/update-patient-coverage-request.json
karate-tests/src/test/java/schemas/searchSchemas/patientCoverageResultEntry.json
specification/components/schemas/Coverage.yaml

Also fixes some max field length and mappings that were broken in the sandbox

SPINEDEM-4908 Changed coverage regex to match DSA

---

poetry.lock
pyproject.toml

Updated authlib, this required the updating of other dependent packages.

SPINEDEM-5285 Update authlib version

---

karate-tests/src/test/java/helpers/patchRequest.feature
karate-tests/src/test/java/helpers/utils.feature
karate-tests/src/test/java/patients/healthcareWorker/updatePatientDetails/addAndRemove.feature
karate-tests/src/test/java/patients/patientAccess/updatePatient.feature

commit 949470e2cfa9a908f843b1c724b81621e8c8bb9f
Author: Laurence Smith <laurence.smith@airelogic.com>
Date:   Thu Jun 18 10:48:40 2020 +0100
+minor
commit 4badf9bf2f39e466f13103cb81bc17b660b78777
Author: Laurence Smith <laurence.smith@airelogic.com>
Date:   Tue Mar 24 12:14:12 2020 +0000
+setstatus beta
commit 12393dc0ea7c7023e0178e3ef10b8fecc3390ce2
Author: Alex Hawdon <alex.hawdon@airelogic.com>
Date:   Fri Feb 28 10:49:28 2020 +0000
empty comit
commit 0e91393036cd5b4638bc5393efd5409667656048
Author: Alex Hawdon <alex.hawdon@airelogic.com>
Date:   Mon Feb 24 12:49:11 2020 +0000
+minor version bump
commit 49a0b39d45e11211d4cab94d865b5b45bbb11235
Merge: 3ab227bf cc278354
Author: Jack Hellowell <jack.hellowell1@nhs.net>
Date:   Tue Jun 17 14:19:27 2025 +0100
Merge branch 'master' into …

Squashed commit of the following:

---

azure/templates/pds-tests-int.yml
karate-tests/src/test/java/patients/appRestricted/getPatient.feature

SPINEDEM-5383 Adding new jwt keys to int environment

---

karate-tests/karate-config.js
karate-tests/src/test/java/patients/TestLocalMockParallel.java
karate-tests/src/test/java/patients/TestMockParallel.java
karate-tests/src/test/java/patients/TestParallel.java
karate-tests/src/test/java/patients/TestSchemaParallel.java
karate-tests/src/test/java/patients/rateLimits/README.md
karate-tests/src/test/java/patients/rateLimits/getPatientDetails.feature
karate-tests/src/test/java/patients/rateLimits/rateLimitSimulation.scala
karate-tests/src/test/java/patients/rateLimits/twoAppsRateLimitsSimulation.scala
manifest_template.yml

* :warning: Enforce rate limit in INT and internal-dev

SPINEDEM-5254 Enforce rate limit in INT

---

karate-tests/src/test/java/patients/recordSharingConsent/searchForApatient.feature

Updated consent sharing test data

SPINEDEM-5474 Updated consent sharing test data

---

karate-tests/src/test/java/patients/healthcareWorker/createPatient/postPatient.feature
karate-tests/src/test/java/patients/healthcareWorker/new-nhs-number-response-template.json

Added test to create a patient with null suffix

SPINEDEM-4240 Added test to create a patient with null suffix

---

karate-tests/src/test/java/patients/appRestricted/searchForPatientUsingMOABcascadingTrace.feature
karate-tests/src/test/java/patients/healthcareWorker/updatePatientDetails/replace.feature

Added MOAB trace related tests

SPINEDEM-5782 Added MOAB trace related tests

---

karate-tests/src/test/java/patients/appRestricted/searchForPatientUsingMOABcascadingTrace.feature

SPINEDEM-5782 updated test data for MOAB related search queries

SPINEDEM-5782 updated test data for MOAB related search queries

---

karate-tests/src/test/java/mocks/sandbox/get-patient-search.js
karate-tests/src/test/java/mocks/stubs/searchResponses/knap_kathy_exact_match.json
postman/patient-demographics-sandbox.postman_collection.json

Added exact match and history match flag related sandbox scenarios and included number allocation end point related tests.

SPINEDEM- 2644 add more sandbox scenarios

---

karate-tests/src/test/java/patients/requestErrors.feature

Added test to check invalid urls.

SPINEDEM-5878 Added test to check invalid urls
